# Generated by Django 2.2.9 on 2021-06-25 11:06

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Products',
            fields=[
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('product_name', models.CharField(default=None, max_length=64, null=True)),
                ('price', models.FloatField(blank=True, max_length=64, null=True)),
            ],
            options={
                'db_table': 'products',
            },
        ),
    ]
